### ISSUE TITLE
libreoffice not opening properly on communitheme.snap

### ISSUE THREAD

**Issue by alculete** [ubuntu/communitheme#350]
the first windows bellow shows libreoffice on ubuntu-session loaded normally
![libreoffice on ubuntu session](https://user-images.githubusercontent.com/2129497/39061969-608b8af8-44c6-11e8-99fb-c9f2dee6e278.png)

the one bellow is from communitheme review 70
![libreoffice on communitheme](https://user-images.githubusercontent.com/2129497/39062028-87e016b4-44c6-11e8-8175-009ba70afe4b.png)

EDIT: This is a snaped version of libreoffice

**Comment by clobrano** [comment]
Opening snapped libreoffice shows the same error of #358, I think it's a possible duplicate, just not 100% sure since the UI is black and not transparent (at least not all of it)

**Comment by Ads20000** [comment]
Is this still broken on Xorg? On Wayland it seems to use Ambiance?

**Comment by jonasmh10** [comment]
Had libreoffice installed with snap and got the issue.
Removed libreoffice with snap and reinstalled with apt-get and now it works fine.
In both instances i was running on the communitheme snap.

**Comment by nicocarbone** [comment]
Is this related to #354 ? If so, it may be soon solved. @kenvandine may have the answer.

**Comment by clobrano** [comment]
@nicocarbone see [my comment just above](https://github.com/ubuntu/gtk-communitheme/issues/350#issuecomment-383978669)

**Comment by clobrano** [comment]
as of today, libreoffice seems still affected by the issue. Not sure if snap needs to be regenerated

**Comment by alculete** [comment]
> EDIT (just a note to myself) maybe because libreoffice still uses gtk2?
will the new GTK2 communitheme solve this issue?

**Comment by clobrano** [comment]
Nope, this isn't a matter of theming, but a problem accessing the files

**Comment by oSoMoN** [comment]
I just tested again with communitheme version 0.1 (revision 614) and libreoffice 6.0.5.2 (revision 67 from the candidate channel), and I'm not seeing the issue any longer. Can anyone confirm this is fixed?

**Comment by clobrano** [comment]
I still have the same issue

```
$ snap info libreoffice
name:    libreoffice
summary: LibreOffice is a powerful office suite including word processing and creation of spreadsheets,
  slideshows and databases
publisher: canonical
contact:   http://www.libreoffice.org/get-help/community-support/
license:   unknown
description: |
  LibreOffice is a powerful office suite – its clean interface and feature-rich tools help you
  unleash your creativity and enhance your productivity. LibreOffice includes several applications
  that make it the most powerful Free and Open Source office suite on the market: Writer (word
  processing), Calc (spreadsheets), Impress (presentations), Draw (vector graphics and flowcharts),
  Base (databases), and Math (formula editing).
commands:
  - libreoffice.base
  - libreoffice.calc
  - libreoffice.draw
  - libreoffice.filebug
  - libreoffice.impress
  - libreoffice
  - libreoffice.math
  - libreoffice.writer
snap-id:      CpUkI0qPIIBVRsjy49adNq4D6Ra72y4v
tracking:     candidate
refresh-date: today at 08:39 CEST
channels:                       
  stable:    6.0.4.2 (65) 479MB -
  candidate: 6.0.5.2 (68) 480MB -
  beta:      ↑                  
  edge:      ↑                  
installed:   6.0.5.2 (68) 480MB -
ubuntu@ubuntu:~$ libreoffice

(soffice:7169): Gtk-WARNING **: 08:50:46.283: Theme parsing error: gtk.css:1:0: Failed to import: Error opening file /snap/communitheme/current/share/themes/Communitheme/gtk-3.0/gtk.css: Permission denied
```

**Comment by oSoMoN** [comment]
Nevermind my previous comment, I wasn't testing properly. I can still see the issue too.
Hopefully [this change](https://git.launchpad.net/~libreoffice/+git/libreoffice-snap/commit/?id=0e58538d71af93eef00c6d73b7767a548208e30d) will do the trick.

**Comment by oSoMoN** [comment]
The theme plugs get auto-connected:

    $ snap interfaces libreoffice | grep themes
    gtk-common-themes:gtk-3-themes  libreoffice
    gtk-common-themes:icon-themes   libreoffice
    gtk-common-themes:sound-themes  libreoffice

But that's not enough, apparently:

    $ snap run libreoffice
    2018/07/17 22:48:24.713316 main.go:192: cannot change mount namespace of snap "libreoffice" according to change mount (/snap/gtk-common-themes/319/share/icons/Adwaita /snap/libreoffice/x1/data-dir/icons/Adwaita none bind,ro 0 0): cannot create writable mimic over "/snap/libreoffice/x1": permission denied
    2018/07/17 22:48:24.714053 main.go:192: cannot change mount namespace of snap "libreoffice" according to change mount (/snap/gtk-common-themes/319/share/icons/DMZ-Black /snap/libreoffice/x1/data-dir/icons/DMZ-Black none bind,ro 0 0): cannot create writable mimic over "/snap/libreoffice/x1": permission denied
    2018/07/17 22:48:24.714599 main.go:192: cannot change mount namespace of snap "libreoffice" according to change mount (/snap/gtk-common-themes/319/share/icons/DMZ-White /snap/libreoffice/x1/data-dir/icons/DMZ-White none bind,ro 0 0): cannot create writable mimic over "/snap/libreoffice/x1": permission denied
    2018/07/17 22:48:24.715171 main.go:192: cannot change mount namespace of snap "libreoffice" according to change mount (/snap/gtk-common-themes/319/share/icons/HighContrast /snap/libreoffice/x1/data-dir/icons/HighContrast none bind,ro 0 0): cannot create writable mimic over "/snap/libreoffice/x1": permission denied
    2018/07/17 22:48:24.715680 main.go:192: cannot change mount namespace of snap "libreoffice" according to change mount (/snap/gtk-common-themes/319/share/icons/Humanity-Dark /snap/libreoffice/x1/data-dir/icons/Humanity-Dark none bind,ro 0 0): cannot create writable mimic over "/snap/libreoffice/x1": permission denied
    2018/07/17 22:48:24.716181 main.go:192: cannot change mount namespace of snap "libreoffice" according to change mount (/snap/gtk-common-themes/319/share/icons/Humanity /snap/libreoffice/x1/data-dir/icons/Humanity none bind,ro 0 0): cannot create writable mimic over "/snap/libreoffice/x1": permission denied
    2018/07/17 22:48:24.716674 main.go:192: cannot change mount namespace of snap "libreoffice" according to change mount (/snap/gtk-common-themes/319/share/icons/Solus /snap/libreoffice/x1/data-dir/icons/Solus none bind,ro 0 0): cannot create writable mimic over "/snap/libreoffice/x1": permission denied
    2018/07/17 22:48:24.717160 main.go:192: cannot change mount namespace of snap "libreoffice" according to change mount (/snap/gtk-common-themes/319/share/icons/Suru /snap/libreoffice/x1/data-dir/icons/Suru none bind,ro 0 0): cannot create writable mimic over "/snap/libreoffice/x1": permission denied
    2018/07/17 22:48:24.717656 main.go:192: cannot change mount namespace of snap "libreoffice" according to change mount (/snap/gtk-common-themes/319/share/icons/communitheme /snap/libreoffice/x1/data-dir/icons/communitheme none bind,ro 0 0): cannot create writable mimic over "/snap/libreoffice/x1": permission denied
    2018/07/17 22:48:24.718144 main.go:192: cannot change mount namespace of snap "libreoffice" according to change mount (/snap/gtk-common-themes/319/share/icons/hicolor /snap/libreoffice/x1/data-dir/icons/hicolor none bind,ro 0 0): cannot create writable mimic over "/snap/libreoffice/x1": permission denied
    2018/07/17 22:48:24.718636 main.go:192: cannot change mount namespace of snap "libreoffice" according to change mount (/snap/gtk-common-themes/319/share/icons/ubuntu-mono-dark /snap/libreoffice/x1/data-dir/icons/ubuntu-mono-dark none bind,ro 0 0): cannot create writable mimic over "/snap/libreoffice/x1": permission denied
    2018/07/17 22:48:24.719145 main.go:192: cannot change mount namespace of snap "libreoffice" according to change mount (/snap/gtk-common-themes/319/share/icons/ubuntu-mono-light /snap/libreoffice/x1/data-dir/icons/ubuntu-mono-light none bind,ro 0 0): cannot create writable mimic over "/snap/libreoffice/x1": permission denied
    2018/07/17 22:48:24.719649 main.go:192: cannot change mount namespace of snap "libreoffice" according to change mount (/snap/gtk-common-themes/319/share/sounds/communitheme /snap/libreoffice/x1/data-dir/sounds/communitheme none bind,ro 0 0): cannot create writable mimic over "/snap/libreoffice/x1": permission denied
    2018/07/17 22:48:24.720153 main.go:192: cannot change mount namespace of snap "libreoffice" according to change mount (/snap/gtk-common-themes/319/share/themes/Adwaita-dark /snap/libreoffice/x1/data-dir/themes/Adwaita-dark none bind,ro 0 0): cannot create writable mimic over "/snap/libreoffice/x1": permission denied
    2018/07/17 22:48:24.720664 main.go:192: cannot change mount namespace of snap "libreoffice" according to change mount (/snap/gtk-common-themes/319/share/themes/Adwaita /snap/libreoffice/x1/data-dir/themes/Adwaita none bind,ro 0 0): cannot create writable mimic over "/snap/libreoffice/x1": permission denied
    2018/07/17 22:48:24.721155 main.go:192: cannot change mount namespace of snap "libreoffice" according to change mount (/snap/gtk-common-themes/319/share/themes/Ambiance /snap/libreoffice/x1/data-dir/themes/Ambiance none bind,ro 0 0): cannot create writable mimic over "/snap/libreoffice/x1": permission denied
    2018/07/17 22:48:24.721638 main.go:192: cannot change mount namespace of snap "libreoffice" according to change mount (/snap/gtk-common-themes/319/share/themes/Arc-Dark /snap/libreoffice/x1/data-dir/themes/Arc-Dark none bind,ro 0 0): cannot create writable mimic over "/snap/libreoffice/x1": permission denied
    2018/07/17 22:48:24.722139 main.go:192: cannot change mount namespace of snap "libreoffice" according to change mount (/snap/gtk-common-themes/319/share/themes/Arc-Darker /snap/libreoffice/x1/data-dir/themes/Arc-Darker none bind,ro 0 0): cannot create writable mimic over "/snap/libreoffice/x1": permission denied
    2018/07/17 22:48:24.722642 main.go:192: cannot change mount namespace of snap "libreoffice" according to change mount (/snap/gtk-common-themes/319/share/themes/Arc /snap/libreoffice/x1/data-dir/themes/Arc none bind,ro 0 0): cannot create writable mimic over "/snap/libreoffice/x1": permission denied
    2018/07/17 22:48:24.723150 main.go:192: cannot change mount namespace of snap "libreoffice" according to change mount (/snap/gtk-common-themes/319/share/themes/Communitheme /snap/libreoffice/x1/data-dir/themes/Communitheme none bind,ro 0 0): cannot create writable mimic over "/snap/libreoffice/x1": permission denied
    2018/07/17 22:48:24.723695 main.go:192: cannot change mount namespace of snap "libreoffice" according to change mount (/snap/gtk-common-themes/319/share/themes/EvoPop-Azure /snap/libreoffice/x1/data-dir/themes/EvoPop-Azure none bind,ro 0 0): cannot create writable mimic over "/snap/libreoffice/x1": permission denied
    2018/07/17 22:48:24.724199 main.go:192: cannot change mount namespace of snap "libreoffice" according to change mount (/snap/gtk-common-themes/319/share/themes/EvoPop /snap/libreoffice/x1/data-dir/themes/EvoPop none bind,ro 0 0): cannot create writable mimic over "/snap/libreoffice/x1": permission denied
    2018/07/17 22:48:24.724539 main.go:192: cannot change mount namespace of snap "libreoffice" according to change mount (/snap/gtk-common-themes/319/share/themes/HighContrast /snap/libreoffice/x1/data-dir/themes/HighContrast none bind,ro 0 0): cannot create writable mimic over "/snap/libreoffice/x1": permission denied
    2018/07/17 22:48:24.724882 main.go:192: cannot change mount namespace of snap "libreoffice" according to change mount (/snap/gtk-common-themes/319/share/themes/Radiance /snap/libreoffice/x1/data-dir/themes/Radiance none bind,ro 0 0): cannot create writable mimic over "/snap/libreoffice/x1": permission denied

    (soffice:5561): Gtk-WARNING **: 22:48:29.094: Theme parsing error: gtk.css:1:0: Failed to import: Erreur lors de l’ouverture du fichier /snap/communitheme/current/share/themes/Communitheme/gtk-3.0/gtk.css : Permission denied

The `data-dir` mount is not created, for some reason:

    $ snap run --shell libreoffice 
    osomon@bribon:/home/osomon$ ls $SNAP/data-dir
    ls: cannot access '/snap/libreoffice/x1/data-dir': No such file or directory

**Comment by oSoMoN** [comment]
Creating the following directories inside the snap does the trick, as a temporary workaround (just creating `data-dir/` is not enough):

    data-dir/icons/
    data-dir/sounds/
    data-dir/themes/

**Comment by oSoMoN** [comment]
[This change](https://git.launchpad.net/~libreoffice/+git/libreoffice-snap/commit/?id=346cfb0b3ba108ef7aea4709c0b064dacc768fa0) hopefully works around the snapd issue reliably.

**Comment by clobrano** [comment]
> I don't seem to be allowed to change the status of the bug, nor assign it to myself, can someone do that for me please?

@oSoMoN, your name does not show in available assignee list :thinking:
