### ISSUE TITLE
Close button in Chrome. 

### ISSUE THREAD

**Issue by jim3872** [ubuntu/communitheme#412]
Mentioned elsewhere but thought I'd highlight it again;

The x and the square doesn't look central to me with chrome in fullscreen. 
![screenshot from 2018-05-04 16-26-42](https://user-images.githubusercontent.com/36636462/39636537-6f15573c-4fb8-11e8-8600-7fc6642763a8.png). 

It's ok in Pop Os

![screenshot from 2018-05-04 16-36-57](https://user-images.githubusercontent.com/36636462/39637037-ccd6f0dc-4fb9-11e8-928a-732580675669.png)

**Comment by clobrano** [comment]
@jim3872 could you tell me in which version of chrome you're experiencing this issue? Just installed chrome on a new PC and I have both custom borders (that it, no communitheme) or no window controls at all when maximized

**Comment by jim3872** [comment]
Version 66.0.3359.181 (Official Build) (64-bit)

**Comment by clobrano** [comment]
The issue is back, even if just stlyghtly (we didn't change anything...)
![screenshot from 2018-07-22 16-12-40](https://user-images.githubusercontent.com/2883614/43046515-1a18f914-8dca-11e8-9c4e-8c3133063d42.png)
