### ISSUE TITLE
Updated: Some appindicators aren't interactive, some do not show up at all

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/communitheme#588]
Previously reported here: https://github.com/ubuntu/gnome-shell-communitheme/issues/95

These are the indicators that are interactive in the communitheme session:
- insync
- google chrome
- telegram
- discord
- skype snap (8.26.76.25 updated at 4.7. from edge channel <3)

These are the indicators that are not interactive in the communitheme session:
- dropbox
- Tomboy
- Diodon

App indicators that do not show up at all in the communitheme session:
- none!

**Comment by clobrano** [comment]
I take advance of this issue to open a discussion about what to do with upstream issues? Shouldn't we  close them since we cannot do anything about it?

**Comment by Feichtmeier** [comment]
> I take advance of this issue to open a discussion about what to do with upstream issues? Shouldn't we close them since we cannot do anything about it?
Somehow you a are right, this one here is kind of informative =)
But actually you are correct

**Comment by Feichtmeier** [comment]
Though Dropbox still didn't fix this I realized that when you triple click the icon, some blue Qt context menu pops up and then the gnome shell pop up.

**Comment by Feichtmeier** [comment]
Since this you can actually use the dropbox in communitheme session (with tripple click the first time) and I have no idea when dropbox will fix this AND in 18.10 we wont have this problem anymore because its only ubuntu session, we close this now :) @clobrano approved decision ;)
