### ISSUE TITLE
Plasma requires special trick for rendering windows' borders

### ISSUE THREAD

**Issue by VandaLHJ** [ubuntu/communitheme#624]
![screenshot_20180713_162559](https://user-images.githubusercontent.com/28790923/42709894-57605e96-86e2-11e8-962c-ae3348cb6891.png)

Rendering on plasma add strange borders instead of shadows. It's most likely linked with rendering engine and lack of cooperation in setting up sensible standards between kde and gnome camps.

Most likely linked with this:

> GTK 3's implementation of CSDs isn't standards compliant and that's why you see these grey borders instead of transparency and shadows. We've been trying for a couple years to find some way around this issue, but the solutions I've proposed haven't panned out. They are as follows:
> 
>     Patch the GTK CSD implementation, at least so RGBA is available. This has been met with resistance over the years as there are always other priorities. When this was first requested, GTK was still undergoing drastic changes per release, so pausing to make sure they had a stable CSD standard for freedesktop.org was not important to GTK developers.
> 
>     Modify KWin to support GTK's implementation of CSDs. This can't be done because GTK doesn't conform to a predictable behavior. If KWin were rearchitected to properly implement a specific GTK version's CSD implementation, it could break as soon as the new version came out. Most other compositors like Compiz or Compton happen to be compatible by chance, whereas KWin's rendering is fairly deep and complex. Changing it could take months of potentially wasted work away from important things like Wayland.
> 
>     Write a KWin effect that shaves off the edges of GTK windows, menus, and tooltips and adds shadows around them. This is very hacky and something I tried to do to no avail as it's rather complicated.
> 
> So, what we've decided on instead is to modify the theme so it gets rid of the grey borders (originally left so you can resize the window) and force window decorations on CSD windows so they can appear more or less correct. You can get part of this if you checkout Breeze-GTK's master branch.
> 
> I should note that native GTK CSD windows might actually behave correctly on Wayland once KWin's xdg_shell is fully up to date. As such, we've altered the theme in such a way that it can work and look fairly correct in both situations. Either way, if we can't get the GTK devs to standardize their CSD implementation in the near future, we may have to remake the theme to take these limitations into account. I should also note that issues like these and GTK's removal of theme engine support have been preventing us from focusing on color scheme support.
> 
> UPDATE: Here's a quick shot of what it looks like. If we can't get any changes into GTK soon, the headerbars will be altered to look like toolbars and appear disabled even if they work in Wayland for the sake of consistency.

**Comment by clobrano** [comment]
I updated the title of the ticket to reflect the content of the request

**Comment by Feichtmeier** [comment]
This theme is currently only developed for the gnome desktop.
That does not mean this may change in the future but currently that's out of our scope.

The other way around, Qt apps in gnome, is what we are working on via gtk2 theme and  qt5-style-plugins though :)

Best regards, thanks for reporting!

**Comment by clobrano** [comment]
Let's say that the patch is not too big we can try to add it, but it is in the lowest prio now
