### ISSUE TITLE
Build system does not apply shell changes

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/communitheme#634]
When changing code in the shell scss files and building, the build seems to finish successfully but the changes are not applied (after shell restart).

This happens to my and @clobrano installation

@didrocks any ideas? :[

**Comment by didrocks** [comment]
Do you mind elaborating? It does work for me:

```sh
$ meson foo
$ cd foo && ninja
[…]
$ ls -rtl gnome-shell/src/
-rw-r--r-- 1 didrocks didrocks 55567 juil. 19 08:11 gnome-shell.css
-rw-r--r-- 1 didrocks didrocks 55907 juil. 19 08:11 gnome-shell-high-contrast.css
$ # try editing ../gnome-shell/src/gnome-shell.scss or ../gnome-shell/src/gnome-shell-sass/_ubuntu-colors.scss
$ ninja
[…]
$ ls -rtl gnome-shell/src/
-rw-r--r-- 1 didrocks didrocks 55951 juil. 19 08:12 gnome-shell-high-contrast.css
-rw-r--r-- 1 didrocks didrocks 60598 juil. 19 08:12 gnome-shell.css
```

-> different timestamp, and changes are available in gnome-shell.css. 
It seems that all files to track and regenerate from are listed, correct? (gnome-shell/src/meson.build)
```
# generate .css files
theme_sources = files([
  'gnome-shell-high-contrast.scss',
  'gnome-shell.scss',
  'gnome-shell-sass/_colors.scss',
  'gnome-shell-sass/_common.scss',
  'gnome-shell-sass/_dock.scss',
  'gnome-shell-sass/_drawing.scss',
  'gnome-shell-sass/_high-contrast-colors.scss',
  'gnome-shell-sass/_ubuntu-colors.scss',
])
```

**Comment by clobrano** [comment]
Correct, the build is fine, however after refreshing the shell the change does not seem applied.

**Comment by didrocks** [comment]
Ah, that was what I mentioned, I didn't test the local install case. How do you install them, what prefix? Ensure that it's in a correct xdg_data_dir path (mind pasting it and where it's installed?)

**Comment by didrocks** [comment]
It's not related to this, but you should really avoid prefix being /usr but rather /usr/local/. I have patched the Shell to support that a long time ago (since the snap time) and that way, you don't mess locally installed content with system-wide ones. I would need to give it a try, can't this morning, but I'll give it a look.

**Comment by clobrano** [comment]
Alright, so we need to change build instructions as well. I'll try again later today

**Comment by Feichtmeier** [comment]
Yes I was doing this the whole time since the instructions told me to :robot: 
Alright let's see if this works

**Comment by Feichtmeier** [comment]
Alrighty I was being stupid several times.

1) I did not uninstall the old build, I think this was the first mistake?
2) I did not realize that another session was made named "Communitheme" and were still in the old session "communitheme on xorg"
3) I was a bit hysterical and deleted all folders and files with communitheme (except the ones in the snap folders) and rebooted, then GDM looked for the last entry and while true gocrazy, luckily I had 3 brain cells left who decided to install the gnome-session in the hope that the GDM settings were updated and it worked so yay I don't need to wipe my disk
4) Now that I double checked successfully if any communitheme folders or files were left (except the ones in snap folders) I cloned the repo again and installed it with the /usr/local/ prefix  and then rebooted but finding that the session was not being installed!

:thinking: 

Icons, Cursor and GTK and shell folders were created. But there is no session selectable in GDM for communitheme and thus I can't use the shell theme.

i probably did so many things wrong that you will tell me to wipe my disk I guess? ;D

**Comment by Feichtmeier** [comment]
Update: completly wiped my "disk" and installed ubuntu 18.04 fresh

Same output as the one above and again NO communitheme session, thus I can't select the gnomeshell theme
I really think something is not working @didrocks

**Comment by Paz-it** [comment]
Stupid question: did you install the the snap?

**Comment by Feichtmeier** [comment]
-.-
No! As I wrote that's all I did :) Ofc I didn't install the snap because the topic is that I need a development environment so I need to build every time I apply changes to the code :D
But I am actually thinking about using the snap for my host and developing on the VM after I figured this out.

**Comment by didrocks** [comment]
Ok, So I found 2 bugs:
1. GDM doesn't have /usr/local in its env, so not looking at session desktop file there.
-> I guess right now, let's default back to /usr for prefix, which I really hate, but as long as you don't install the packaged version, it's fine :( The issue would be to SRU that on bionic.
2. GNOME Shell doesn't like mode starting with a capital letter. It's doing some lowercasing in matching the mod name.

I'm going to do a PR for both.

**Comment by Feichtmeier** [comment]
@didrocks  thanks for looking into that :tada: 

Do you know if those two files 
/usr/share/xsessions/Ubuntu with communitheme snap
/usr/share/wayland-sessions/Ubuntu with communitheme snap 

Are there by some deb default or did I create them with meson? Because I deleted them @.@ If there were installed by default, any way to restore them? (deleted with shift ^^)

**Comment by didrocks** [comment]
No worry, please check the PR!

The 2 files you mention are coming from the ubuntu-session package. This is why we shouldn't touch at anything in /usr in general, this is for the system ;)

To reinstall them, just reinstall the package: `sudo apt install ubuntu-session --reinstall`.
