### ISSUE TITLE
gnome-shell: Did not find color property '-slider-border-color'

### ISSUE THREAD

**Issue by didrocks** [ubuntu/communitheme#635]
It seems that property has been removed, spawning the logs in warning. It should be readded.

**Comment by Feichtmeier** [comment]
Oh okay I'll do that

**Comment by didrocks** [comment]
Another one: (gnome-shell:2629): St-WARNING **: 16:20:24.819: Ignoring length property that isn't a number at line 2253, col 24

I think it would be great that we try the session sometimes with `journalctl -f /usr/bin/gnome-shell` and look at what's in there which is related to the theme.

**Comment by clobrano** [comment]
closed by #638
