### ISSUE TITLE
dock is not correctly installed

### ISSUE THREAD

**Issue by Feichtmeier** [ubuntu/communitheme#637]
I were a bit too fast there (was so happy to see the theme that I didn't look closely)

![screenshot from 2018-07-19 18-22-27](https://user-images.githubusercontent.com/15329494/42956604-b3f35526-8b80-11e8-9e64-f84780bc4ea6.png)

@didrocks I did a second fresh install to be sure and installed with prefix=/usr

BUT

The dock is unfinnished/mixed, like a mix of the ubuntu session and the communitheme session. 

- The unread badges are  red and flat like in the "ambiance"-shell-theme and they overlap the green badges of our theme (you can't see this in that screenshot)
- the active Windows indicators also have an overlap with ambiance orange on the darker communitheme orange (you need to zoom)
- The dock has  transparency in full screen mode (pretty easy to see in this screenshot)

**Comment by Feichtmeier** [comment]
Update: after the 3. re-install today I used the snap from edge now, because I need my computer to work again (and yet look good :P) :cry: 
Works fine: dock, shell, icons, sound, cursors :+1: 

Developing in the VM now again (I dodged this until now because I often code in the train without AC and VM is quiet heavy on the battery :dancer: but third time ubuntu reinstall was a bit too much now /sleep )

**Comment by didrocks** [comment]
Well, remember this is for dev only, it doesn't impact snap or install package installation. Thanks for the detailed explanation!

You can achieve the same with symlinks if you prefer :)
I'm puzzled though why the Shell is themed and not the Dock. But while writing exactly this, I think I got it: the session name is different! I don't know what was your setup previously, but It never worked on any other session than the snap, thinking about it, so I don't know how you forced using the system version.

The explanation is that we are lacking an empty file in `/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/` which matches the mode name.
So, I'm going to propose a branch and fix it, but in theory, you just need to `sudo touch usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/communitheme.css` and you should be fine, letting your gnome-shell.css overriding the extension.
