### ISSUE TITLE
README File Clarity: How will I know when Communitheme and other planned features are added to 18.10 daily builds?

### ISSUE THREAD

**Issue by duke7553** [ubuntu/communitheme#640]
![1810_theme_docs](https://user-images.githubusercontent.com/20365014/43026275-fd615d80-8c42-11e8-85ca-37931cb9dfaa.png)
My apologies if the relevance of this issue is questioned. However, the snippet of the README file above does not specify an exact date regarding the implementation of Communitheme and other planned features in the 18.10 daily builds. This is understandable, as planning new features is complicated work. I would just like to know how I can stay informed of feature additions (addition of Communitheme, etc) to the daily builds. Of course, reading the official kernel change-logs each day isn't necessary ;)

**Comment by Feichtmeier** [comment]
Sorry but is just wrong. If you want to ask questions like these join us on
https://community.ubuntu.com/
There is even a thread where I asked similar questions
